#!/usr/bin/env bash

source ./image_versions

docker pull nasoym/request_container_service_docker_controller:${controller_version}
docker pull nasoym/request_container_service_request_router:${request_router_version}
docker pull nasoym/request_container_service_authentication:${authentication_version}
docker pull nasoym/request_container_service_cron_trigger:${cron_trigger_version}

